# Generated by Django 5.2.7 on 2025-10-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodresponse',
            name='what_do_you_enjoy',
            field=models.JSONField(),
        ),
    ]
