# Generated by Django 5.2.7 on 2025-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_alter_moodresponse_what_do_you_enjoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodresponse',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
