# Generated by Django 5.2.7 on 2025-11-04 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wake_up_time', models.TimeField(blank=True, null=True)),
                ('sleep_time', models.TimeField(blank=True, null=True)),
                ('enable_meals', models.BooleanField(default=True)),
                ('breakfast_time', models.TimeField(blank=True, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('dinner_time', models.TimeField(blank=True, null=True)),
                ('break_frequency', models.CharField(blank=True, choices=[('hourly', 'Every hour'), ('couple_hours', 'Every 2-3 hours'), ('twice_daily', 'Twice per day'), ('flexible', 'As needed')], max_length=20)),
                ('break_duration', models.CharField(blank=True, choices=[('quick', 'Quick (5-10 min)'), ('standard', 'Standard (15-20 min)'), ('extended', 'Extended (30+ min)')], max_length=16)),
                ('schedule_strictness', models.CharField(blank=True, choices=[('relaxed', 'Relaxed'), ('moderate', 'Moderate'), ('precise', 'Precise')], max_length=16)),
                ('preferred_start_time', models.TimeField(blank=True, null=True)),
                ('preferred_end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
