# Generated by Django 5.2.7 on 2025-12-05 08:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('place_id', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hotel_address', models.CharField(blank=True, max_length=255)),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('hotel_place_id', models.CharField(blank=True, max_length=255)),
                ('hotel_check_in', models.DateTimeField(blank=True, null=True)),
                ('hotel_check_out', models.DateTimeField(blank=True, null=True)),
                ('wake_up_time', models.TimeField()),
                ('bed_time', models.TimeField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('trip_purpose', models.CharField(choices=[('leisure', 'Leisure'), ('family', 'Family'), ('adventure', 'Adventure'), ('relaxed', 'Relaxed'), ('business', 'Business')], default='leisure', max_length=32)),
                ('energy_level', models.CharField(choices=[('easy', 'Easy-going'), ('balanced', 'Balanced'), ('high', 'High energy')], default='balanced', max_length=16)),
                ('include_breakfast', models.BooleanField(default=True)),
                ('include_lunch', models.BooleanField(default=True)),
                ('include_dinner', models.BooleanField(default=True)),
                ('dietary_notes', models.TextField(blank=True)),
                ('mobility_notes', models.TextField(blank=True)),
                ('downtime_required', models.BooleanField(default=False)),
                ('party_adults', models.PositiveIntegerField(default=1)),
                ('party_children', models.PositiveIntegerField(default=0)),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True)),
                ('arrival_airport', models.CharField(blank=True, max_length=64)),
                ('departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('departure_airport', models.CharField(blank=True, max_length=64)),
                ('arrival_flight_number', models.CharField(blank=True, max_length=16)),
                ('departure_flight_number', models.CharField(blank=True, max_length=16)),
                ('auto_suggest_hotel', models.BooleanField(default=False)),
                ('overall_budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('ai_itinerary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_code', models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Accommodation', 'Accommodation'), ('Transportation', 'Transportation'), ('Food & Dining', 'Food & Dining'), ('Activities', 'Activities'), ('Shopping', 'Shopping'), ('Other', 'Other')], max_length=50)),
                ('custom_category', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='itinerary.itinerary')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.CharField(blank=True, max_length=64)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_times', to='itinerary.itinerary')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('wake_override', models.TimeField(blank=True, null=True)),
                ('bed_override', models.TimeField(blank=True, null=True)),
                ('constraints', models.TextField(blank=True)),
                ('must_do', models.TextField(blank=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itinerary.itinerary')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('itinerary', 'day_number')},
            },
        ),
    ]
