# Generated by Django 5.2.7 on 2025-12-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='arrival_airline',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='departure_airline',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
