# Generated by Django 5.2.7 on 2025-12-05 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itinerary', '0002_itinerary_arrival_airline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL),
        ),
    ]
