# Generated by Django 5.2.8 on 2025-12-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_itinerary_ai_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='access_code',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
