# Generated by Django 5.2.8 on 2025-12-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_itinerary_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='access_code',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
