# Generated by Django 5.2.7 on 2025-12-05 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_alter_itinerary_access_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='breaktime',
            name='purpose',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='day',
            name='bed_override',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='constraints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='day',
            name='must_do',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='day',
            name='wake_override',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='arrival_airline',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='arrival_airport',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='arrival_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='arrival_flight_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='auto_suggest_hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='departure_airline',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='departure_airport',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='departure_flight_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='dietary_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='downtime_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='energy_level',
            field=models.CharField(choices=[('easy', 'Easy-going'), ('balanced', 'Balanced'), ('high', 'High energy')], default='balanced', max_length=16),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotel_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotel_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotel_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotel_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='include_breakfast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='include_dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='include_lunch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='mobility_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='overall_budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='party_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='party_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip_purpose',
            field=models.CharField(choices=[('leisure', 'Leisure'), ('family', 'Family'), ('adventure', 'Adventure'), ('relaxed', 'Relaxed'), ('business', 'Business')], default='leisure', max_length=32),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL),
        ),
    ]
