"""
Django settings for Wanderly project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

 # Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------- Google Auth ---------------------------------

# Load the root .env first (same directory as manage.py)
root_env = BASE_DIR / ".env"
if root_env.exists():
    load_dotenv(root_env, override=True)

# Ensure the GOOGLE_OAUTH_CLIENT_ID environment variable is set,
# but allow a placeholder during tests
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
# Ensure the GOOGLE_PLACES_API_KEY environment variable is set, but allow a placeholder during tests
GOOGLE_PLACES_API_KEY = os.environ.get('GOOGLE_PLACES_API_KEY')

running_tests = (
    'test' in sys.argv
    or 'pytest' in sys.argv[0]
    or os.environ.get('PYTEST_CURRENT_TEST')
)

if running_tests:
    GOOGLE_OAUTH_CLIENT_ID = GOOGLE_OAUTH_CLIENT_ID or 'test-google-client-id'
    GOOGLE_PLACES_API_KEY = GOOGLE_PLACES_API_KEY or 'test-api-key'
else:
    if not GOOGLE_OAUTH_CLIENT_ID:
        raise ValueError(
            'GOOGLE_OAUTH_CLIENT_ID is missing.'
            'Have you put it in a file at core/.env ?'
        )
    if not GOOGLE_PLACES_API_KEY:
        raise ValueError(
        'GOOGLE_PLACES_API_KEY is missing. '
        'Have you put it in a file at core/.env ?'
    )

# We need these lines below to allow the Google sign in popup to work.
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

# --------------------------------------------------------------

# --------------------- Google Routes API Keys -----------------

# Set API keys (already loaded from .env above)
GOOGLE_MAPS_BROWSER_KEY = os.getenv("GOOGLE_MAPS_BROWSER_KEY", "")
GOOGLE_ROUTES_SERVER_KEY = os.getenv("GOOGLE_ROUTES_SERVER_KEY", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
# --------------------------------------------------------------

# --------------------- Django Email Setup -----------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "wanderlyhelper@gmail.com"
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "Wanderly <no-reply@wanderly.com>"
PASSWORD_RESET_TIMEOUT = 300 # five minutes.
# --------------------------------------------------------------


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Determine environment
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')

# Hosts
if ENVIRONMENT == 'production':
    ALLOWED_HOSTS = [
        os.environ.get('RENDER_EXTERNAL_HOSTNAME', ''),
        'wanderly-m0s3.onrender.com',
        'wanderly.social',
        'www.wanderly.social',
        '.onrender.com',
    ]
else:
    ALLOWED_HOSTS = [
        "app-cruzcs4300-19.devedu.io",
        "app-roshea-19.devedu.io",
        "app-gwilli17-19.devedu.io",
        "app-jgfuze-19.devedu.io",
        "localhost",
        "http://0.0.0.0:3000/",
    ]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'budgets',
    'time_preferences',
    'home',
    'mood',
    'google_routing',
    'user_auth',
    'places_auto_complete',
]

# Toggle JSON export of planner submissions (writes JSON under each planner app when True)
CREATE_JSON_OUTPUT = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Wanderly.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Wanderly.wsgi.application'

# Database
if ENVIRONMENT == 'production':
    # Render provides DATABASE_URL environment variable
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development database (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Production-specific settings
if ENVIRONMENT == 'production':
    # Security settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = False
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    CSRF_USE_SESSIONS = False

    # Trusted origins for CSRF
    CSRF_TRUSTED_ORIGINS = [
    f"https://{os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')}",
    'https://wanderly-m0s3.onrender.com',
    'https://wanderly.social',
    'https://www.wanderly.social',
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://app-roshea-19.devedu.io',
        'http://app-jgfuze-19.devedu.io',
        "https://app-cruzcs4300-19.devedu.io",
        "https://app-gwilli17-19.devedu.io",
        'http://localhost',
    ]
